name       : kaa-base
version    : 0.6.0
release    : 2
source     :
    - https://github.com/freevo/kaa-base/archive/0.6.0.tar.gz : 5003ec60640eb010f3f324854adefeeb639d84253fef8a0a8aaff58f325fc97a
license    : GPL-2.0
component  : programming
summary    : Kaa.base is an LGPL-licensed generic Python application framework with
    an emphasis on asynchronous programming.
description: |
    Kaa is an umbrella project comprising a set of Python modules, mostly inclined toward solving problems in the domain of multimedia. kaa.base is an LGPL-licensed generic application framework, providing the foundation for other modules within Kaa, and can be used in any type of project, from small event-driven tools, to larger, complex applications. The Kaa Application Framework includes a mainloop facility with an API for signals and callbacks, timers, thread and subprocess management, local IO and sockets (with TLS support), inter-process communication, and much more. Kaa also – and perhaps most importantly – provides a rich, practically magical API for asynchronous programming. Threads and coroutines in combination with InProgress objects, which are used extensively throughout Kaa, allow you to implement complex state machines responding to asynchronous events in very compact, readable code.
build      : |
    %python_setup
install    : |
    %python_install
